test-item:
	PYTHONPATH=. python -m app.tests.test_item_model

test-service:
	PYTHONPATH=. python -m app.tests.test_item_service

test-handler:
	PYTHONPATH=. python -m app.tests.test_item_handlers

test-all:
	PYTHONPATH=. python -m app.tests.test_item_model
	PYTHONPATH=. python -m app.tests.test_item_service